name = "UnifiedBackend"
uuid = "53203a36-6468-4ce1-9d2a-5f04ad17d58e"
authors = ["madmax"]
version = "0.0.1"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[weakdeps]
AMDGPU = "21141c5a-9bdb-4563-92ae-f87d6854732e"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[extensions]
CUDAExt = "CUDA"
ROCmExt = "AMDGPU"